const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const values={},claims=new Map();
let offline=false;
const window={localStorage:{getItem:k=>values[k]||null,setItem:(k,v)=>{values[k]=v;}},ForgeAPI:{config:{key:'public'},rpc:async(name,args)=>{
  if(offline)throw Error('offline');
  const id=args.p_student_id, rows=[...claims.values()].filter(r=>r.id===id);
  if(name==='get_student_match_xp')return {xp_total:rows.reduce((n,r)=>n+r.xp,0)};
  const key=id+'|'+args.p_day+'|'+args.p_bank;
  if(!claims.has(key))claims.set(key,{id,xp:args.p_pairs*5});
  return {awarded:claims.get(key).xp===args.p_pairs*5&&rows.length===claims.size-1,xp:rows.some(r=>r===claims.get(key))?0:args.p_pairs*5,xp_total:[...claims.values()].filter(r=>r.id===id).reduce((n,r)=>n+r.xp,0)};
}}};
window.window=window;
vm.createContext(window);
vm.runInContext(fs.readFileSync('scripts/forge-rewards.js','utf8'),window);
const rewards=window.ForgeRewards;
const ctx=id=>({studentId:id,classCode:'CLASS',studentCode:'ABCD'});
(async()=>{
  rewards.rememberQuizXp('a',90);
  assert.strictEqual(rewards.unlocked('a','meadow'),false);
  assert.strictEqual(rewards.unlocked('new','ocean'),true);
  assert.strictEqual(rewards.unlocked('new','violet'),true);
  let first=await rewards.awardMatch(ctx('a'),'topic-1',4,'2026-10-07');
  assert.strictEqual(first.xp,20);assert.strictEqual(first.synced,true);
  assert.strictEqual((await rewards.awardMatch(ctx('a'),'topic-1',4,'2026-10-07')).xp,0);
  assert.strictEqual(rewards.total('a'),110);
  assert.strictEqual(rewards.unlocked('a','meadow'),true);
  // A fresh browser sees the server balance and cannot claim the same topic.
  delete values['forge-rewards:a'];
  await rewards.load(ctx('a'));
  assert.strictEqual(rewards.read('a').matchXp,20);
  assert.strictEqual((await rewards.awardMatch(ctx('a'),'topic-1',4,'2026-10-07')).xp,0);
  offline=true;
  const saved=await rewards.awardMatch(ctx('a'),'topic-2',3,'2026-10-07');
  assert.strictEqual(saved.xp,15);assert.strictEqual(saved.synced,false);
  assert.strictEqual(rewards.read('a').matchXp,35);
  offline=false;
  await rewards.load(ctx('a'));
  assert.strictEqual(rewards.read('a').matchXp,35);
  assert.strictEqual(rewards.read('a').pending.length,0);
  values['forge-rewards:legacy']=JSON.stringify({matchXp:15,quizXp:0,rounds:{'2026-10-07|old-topic':true}});
  assert.strictEqual(rewards.read('legacy').matchXp,15);
  await rewards.load(ctx('legacy'));
  assert.strictEqual(rewards.read('legacy').matchXp,15);
  assert.strictEqual(rewards.read('legacy').pending.length,0);
  console.log('Reward tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
