const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const values={};
const window={localStorage:{getItem:k=>values[k]||null,setItem:(k,v)=>{values[k]=v;}}};
window.window=window;
vm.createContext(window);
vm.runInContext(fs.readFileSync('scripts/forge-rewards.js','utf8'),window);
const rewards=window.ForgeRewards;
rewards.rememberQuizXp('student-a',290);
assert.strictEqual(rewards.awardMatch('student-a','topic-1',4,'2026-10-07'),20);
assert.strictEqual(rewards.awardMatch('student-a','topic-1',4,'2026-10-07'),0);
assert.strictEqual(rewards.total('student-a'),310);
assert.strictEqual(rewards.unlocked('new-student','ocean'),true);
assert.strictEqual(rewards.unlocked('new-student','violet'),true);
assert.strictEqual(rewards.unlocked('new-student','meadow'),false);
assert.strictEqual(rewards.unlocked('student-a','meadow'),true);
assert.strictEqual(rewards.unlocked('student-a','coral'),false);
rewards.rememberQuizXp('student-c',1500);
assert.strictEqual(rewards.unlocked('student-c','coral'),true);
assert.strictEqual(rewards.unlocked('student-c','gold'),false);
rewards.rememberQuizXp('student-c',3000);
assert.strictEqual(rewards.unlocked('student-c','gold'),true);
assert.strictEqual(rewards.unlocked('student-a','folio'),false);
assert.strictEqual(rewards.awardMatch('student-a','topic-1',3,'2026-10-08'),15);
assert.strictEqual(rewards.awardMatch('student-b','topic-1',4,'2026-10-07'),20);
assert.strictEqual(rewards.total('student-b'),20);
assert.strictEqual(rewards.read('student-a').matchXp,35);
console.log('Reward tests passed.');
